services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4004:3000"
    env_file:
      - ./.env.local
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm install --frozen-lockfile && pnpm dev --hostname 0.0.0.0"
